# 例外
# NameError（名前のエラー）
# TypeError（データ型のエラー）
# ValueError（値のエラー）

# try catch

# try:
# 	処理
# except ValueError:
# 	エラーが発生した時の処理